### ISSUE TITLE
Create Project / ROS-Node blueprint and technical toolstack

### ISSUE THREAD

**Issue by Berghojo** [ll7/paf21-1#13]
Task:
- define an approach how to deploy the project components and glue them together
- define a blueprint for a typical ROS node using rospy (CMake + Dockerfile + ROS Launchfile + pip dependencies)

Goal:
- a scalable approach that can be used to start creating the first components and make a quick prototype
- a diagram outlining the deployment approach

**Comment by AxelBo** [comment]
duplicate
