### ISSUE TITLE
Checking the documentation and the project status.

### ISSUE THREAD

**Issue by ll7** [ll7/paf21-1#152]
see the wiki as well.

https://digicampus.uni-augsburg.de/dispatch.php/course/scm/acc5369af022d5ed4e19af0befdc7153?cid=53e41a88f521da0b4d9ccdd9fc7cec27

Ziel:  
  - schnelle Einarbeitung  
  - Wiederverwendbarkeit  
Inline:   
  - was gemacht wird (wenn nicht eindeutig aus dem naming hervor geht)  
  - wie etwas gemacht wird  
  - Funktionen & Klassen  
    - [docstrings](https://peps.python.org/pep-0257/multi-line-docstrings)  
      - in und output  
Extern: im Wiki oder Docs Folder (verlinken aus dem Readme)  
  - Installationsanleitung und Systemvoraussetzungen  
  - Beispiel Verwendung  
  - Übersicht über den Programmablauf/-aufbau  
    - Darstellung der Zusammenhänge der Subpakete  
      - https://github.com/ll7/psaf1/blob/master/docs/modules_diagram.png  
      - https://github.com/ll7/psaf2/blob/main/documentation/package_overview.svg  
    - Aufgabenübersicht der Subpakete  
      - Program XY hat diese Aufgabe und diese Ein- und Ausgänge  
    - Warum etwas so gemacht wird  
  - Pakete dokumentieren  
    - Warum etwas so gemacht wird  
      - Hintergrundinformationen und Überlegungen  
    - Schnittstellen und Abhängigkeiten  
    - Funktionsumfang  
  - Known Issues   
    - Idealerweise mit Vermutung oder Begründung der Ursache und Hinweisen zu Future Work.

**Comment by ll7** [comment]
https://github.com/ll7/paf21-1/wiki/Development-Machine-Setup-(NVIDIA-Docker)

where is git-lfs needed and where is the repo?

**Comment by ll7** [comment]
wiki files from https://github.com/ll7/paf21-1.wiki.git

Architecture-Model.md
CARLA-ROS-Bridge-Tutorial.md
Decision-Making-Component.md
Definition-of-Done.md
Development-Machine-Setup-(NVIDIA-Docker).md
Development-Workflow.md
files.txt
Global-Planner.md
Home.md
How-To:-Create-new-integration-test-.bag-files.md
Interfaces-and-Dataflow.md
Lab-PC-User-Account-Setup.md
Lane-Keeping-Assistant-(Obsolete).md
Local-Planner.md
Obstacle-Observer.md
Perception.md
ROS-Test-Node-for-CARLA---First-Walkthrough.md
Speed-State-Machine.md
Summary-of-Last-Year's-Project-of-Team-1.md
Summary-of-Last-Year's-Project-of-Team-2.md
Summary-‐-Tesla's-Self-Driving-Approach.md
Tutorial-‐-Run-ROS-GUI-Applications-with-Docker.md
Vehicle-Controller.md

**Comment by ll7** [comment]
# General Readme

https://github.com/ll7/paf21-1/blob/master/README.md

**Comment by ll7** [comment]
# Components Readme

https://github.com/ll7/paf21-1/blob/master/components/README.md#run-the-integration-tests

When and why should I run the integration tests?

**Comment by ll7** [comment]
# Scenarios

I expected they integrated the repository. Instead they have manually copied paf_competition_manager

**Comment by ll7** [comment]
# `./launch.sh`

How do I use the launch file? https://github.com/ll7/paf21-1/blob/master/launch.sh#L7 does the first parameter has to be a string pointing towards a confing file? How is the default config file found? Don't they need the relative path?

**Comment by Bonifatius94** [comment]
> # Wiki Developement Machine Setup Nvidia Docker
> where is git-lfs needed and where is the repo?

The git-lfs extension is not needed anymore. But it's no harm to install it anyways, so we kept it inside our docs.

> adding the recommended extensions in a .vscode folder

That's actually a really bad idea because the .vscode folder is in our .gitignore for a reason. Each developer has the right to use the code editor of his/her choice. Relying on configuration in .vscode would force people to use VSCode which is not intended. 

The whole point of our Docker setup is to make the project self-contained in a way that there's no hidden information / tooling required except for Docker and a plain text editor. That way we achieve maximum freedom when it comes to development.

**Comment by Bonifatius94** [comment]
> # General Readme
> 
> https://github.com/ll7/paf21-1/blob/master/README.md
> 
> https://github.com/ll7/paf21-1/blob/master/README.md#quick-start
> 
> the tutorial for docker was good, but what does step 3) look like? https://github.com/ll7/paf21-1/blob/master/README.md?plain=1#L33
> does this only mean that one should execute the `./launch.sh` ?

yes, it's outlined in the shell script example a few lines below https://github.com/ll7/paf21-1/blob/master/README.md?plain=1#L39

> does the shutdown script stop the launch processes?

yes, it collects Docker logs, terminates all containers launched and prints the simulation time elapsed.

**Comment by Bonifatius94** [comment]
> How do I use the launch file? https://github.com/ll7/paf21-1/blob/master/launch.sh#L7 does the first parameter has to be a string pointing towards a confing file? How is the default config file found? Don't they need the relative path?

I admit, it's a bit convoluted for readers that are not familiar to bash scripting. But yeah, the usage should be somewhat clear now, hopefully. (added a usage section in the launch.sh file to clarify)

**Comment by Bonifatius94** [comment]
> # Scenarios
> 
> I expected they integrated the repository. Instead they have manually copied paf_competition_manager
> 
> How do I execute a scenario?

There was no point in adding a git submodule or something similar when we don't even use a single file from that repo. The component just consists of a single Python script processing nav_msgs/Odometry messages.

**Comment by ll7** [comment]
> > adding the recommended extensions in a .vscode folder
> 
> That's actually a really bad idea because the .vscode folder is in our .gitignore for a reason. Each developer has the right to use the code editor of his/her choice. Relying on configuration in .vscode would force people to use VSCode which is not intended.
> 
> The whole point of our Docker setup is to make the project self-contained in a way that there's no hidden information / tooling required except for Docker and a plain text editor. That way we achieve maximum freedom when it comes to development.

Okay, I thought that a vscode extension recommendation doesn't affect anyone without vscode, as long as everything works without vscode? And you can ignore every recommendation, if you are using vscode but don't want to use the extension?

**Comment by Bonifatius94** [comment]
> > > adding the recommended extensions in a .vscode folder
> > 
> > 
> > That's actually a really bad idea because the .vscode folder is in our .gitignore for a reason. Each developer has the right to use the code editor of his/her choice. Relying on configuration in .vscode would force people to use VSCode which is not intended.
> > The whole point of our Docker setup is to make the project self-contained in a way that there's no hidden information / tooling required except for Docker and a plain text editor. That way we achieve maximum freedom when it comes to development.
> 
> Okay, I thought that a vscode extension recommendation doesn't affect anyone without vscode, as long as everything works without vscode? And you can ignore every recommendation, if you are using vscode but don't want to use the extension?

VSCode scans the project for characteristic files and patterns. That way, it will most certainly suggest you the right extensions without any explicit specifications. The information is already encoded in the project's files, no need to repeat it.
