### ISSUE TITLE
Rviz doesnt display rgb cameras

### ISSUE THREAD

**Issue by ll7** [ll7/paf21-1#154]
![image](https://user-images.githubusercontent.com/32880741/161596028-5e746271-f088-41d7-8230-6ab39dd15d99.png)

**Comment by ll7** [comment]
#152

**Comment by ll7** [comment]
![image](https://user-images.githubusercontent.com/32880741/161598804-58cedaea-6d38-44fb-b86f-f19ccc0ca2f4.png)

auf einmal funktioniert es doch

**Comment by Bonifatius94** [comment]
Du bist nur etwas ungeduldig. Unser System lässt sich immer 20-30 Sekunden Zeit, um sich einzupendeln.

Bei einem reinen Docker Approach würdest du das Simulator-Fenster gar nicht erst sehen. Dann wäre es auch 1000 Mal weniger verwirrend, dass einfach ein paar Sekunden lang nix passiert. Aber klar, irgendwas für die Responsiveness hätte man sich schon überlegen können, dass es sich für den User besser anfühlt, zu warten.

Wir schauen es uns auf jeden Fall nochmal an und versuchen, eine Lösung für die Timeouts zu finden, damit das Projekt verlässlich hochstartet.

**Comment by ll7** [comment]
Die Objekte haben sich bereits bewegt und auch nach 20-30 Sekunden war kein RGB und kein Segmentation Bild zu sehen. Es hat erst beim Neustart geklappt. Ich kann das Problem allerdings nicht reproduzieren.
