### ISSUE TITLE
ROS Test Node for CARLA

### ISSUE THREAD

**Issue by Bonifatius94** [ll7/paf21-1#3]
Task:
- find out how to interact with CARLA and make a car move using a ROS node
- document the whole thing, so we can use this as a blueprint for other ROS nodes

Goal:
- there's a running CARLA simulation moving a car around
- the car needs to be doing what our ROS node tells it to do
- ~~try out as many CARLA signals as possible (ideally all switches of a vehicle used for driving)~~
- it's not expected to have a perfectly driving car, just send random signals and see whether the system responds to it

**Comment by Bonifatius94** [comment]
we didn't write our own ROS node, just used *rostopic echo* / *rostopic pub* for reading / sending CARLA sensor information

**Comment by paschok** [comment]
Reading is done by written own subscriber file
