### ISSUE TITLE
Discussion: Is ROS needed?

### ISSUE THREAD

**Issue by Berghojo** [ll7/paf21-1#8]
**Task:**
Initial Tests showed we can access CARLA and communicate between nodes without using ROS. Therefore we want to investigate whether it's reasonable not to use ROS for this kind of project type

**Goal:**
Find out if we should stick to using the CARLA ROS bridge or whether we may attach to the CARLA PythonAPI directly

**Comment by Bonifatius94** [comment]
**Reasons for ROS:**
- the messaging middleware comes for free, no need to think about how to exchange messages between system components, just register input and output topics in a launchfile and that's it, ROS will do the transmission for you
- it provides the ability to record messages between each and every component in the data flow and replay them in the same chronological manner as they were recorded -> data-driven development, data flow abstraction, isolated component testing, ...
- allows for a loosely-coupled microservice-like architecture with lots of flexibility
- multiple components can listen to the same topics simultaneously, ROS does the forwarding seemlessly
- ROS nodes can bei implemented in C++, Python, Java, R, etc. which makes any package lib of those very different tech stacks potentially available to the system, so there's a giant toolbox that can be used to solve various problems
- if designed correctly, the core of each component is properly decoupled from the message exchange mechanism, so it shouldn't be too hard to exchange the middleware anyways in case there are severe reasons against ROS

**Reasons against ROS:**
- the setup is really complicated (can be automated though to make it less painful)
- all components need to be compiled against the *.msg files which causes coupling
- the binary distribution mechanism is rather complex (deploying each ROS nodes inside a separate Docker container can help with that)
